on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PACKAGE_NAME: "@${{ github.repository }}"
  PACKAGE_VERSION: "1.0.0-g${{ github.sha }}"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: generate package.json
      run: |
        LOWERCASE_PACKAGE_NAME=${PACKAGE_NAME,,}
        cat > package.json << EOM
        {
          "name": "$LOWERCASE_PACKAGE_NAME",
          "version": "$PACKAGE_VERSION",
          "description": "",
          "main": "index.js",
          "author": "",
          "license": "ISC"
        }
        EOM
    - run: npm pack
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  install:
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
    - name: npm install
      run: |
        LOWERCASE_PACKAGE_NAME=${PACKAGE_NAME,,}
        npm install $LOWERCASE_PACKAGE_NAME@$PACKAGE_VERSION
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
